export type Category = {
  slug: string
  name: string
  description: string
  cover: string
  count: number
  photos: { src: string; caption: string }[]
}

const allPhotos = [
  { src: '/images/Acesshirt.jpg', caption: 'ACES Shirt' },
  { src: '/images/codefest.jpg', caption: 'CodeFest' },
  { src: '/images/homeImage.png', caption: 'ACES Community' },
  { src: '/images/Jersey.jpg', caption: 'ACES Jersey' },
  { src: '/images/Nocte.jpg', caption: 'Nocte' },
  { src: '/images/official.jpg', caption: 'Official Group Photo' },
  { src: '/images/Trip.jpg', caption: 'ACES Trip' },
  { src: '/images/About.jpg', caption: 'About ACES' },
  { src: '/images/aces-group-photo.png', caption: 'ACES Group Photo' },
]

const photos_aces_week = [
  { src: '/images/gallery/Aces week/1.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/2.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/3.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/4.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/5.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/6.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/7.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/8.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/9.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/10.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/11.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/12.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/13.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/14.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/15.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/16.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/17.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/18.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/19.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/20.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/21.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/22.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/23.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/24.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/25.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/26.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/27.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/28.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/29.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/30.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/31.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/32.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/33.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/34.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/35.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/36.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/37.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/38.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/39.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/40.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/41.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/42.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/43.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/44.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/45.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/46.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/47.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/48.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/49.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/50.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/51.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/52.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/53.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/54.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/55.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/56.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/57.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/58.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/59.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/60.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/61.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/62.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/63.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/64.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/65.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/66.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/67.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/68.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/69.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/70.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/71.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/72.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/73.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/74.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/75.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/76.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/77.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/78.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/79.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/80.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/81.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/82.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/83.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/84.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/85.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/86.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/87.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/88.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/89.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/90.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/91.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/92.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/93.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/94.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/95.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/96.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/97.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/98.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/99.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/100.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/101.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/102.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/103.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/104.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/105.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/106.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/107.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/108.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/109.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/110.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/111.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/112.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/113.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/114.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/115.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/116.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/117.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/118.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/119.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/120.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/121.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/122.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/123.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/124.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/125.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/126.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/127.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/128.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/129.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/130.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/131.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/132.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/133.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/134.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/135.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/136.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/137.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/138.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/139.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/140.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/141.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/142.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/144.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/145.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/146.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/147.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/148.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/149.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/150.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/151.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/152.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/153.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/154.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/155.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/156.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/157.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/158.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/159.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/160.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/161.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/162.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/163.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/164.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/165.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/166.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/167.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/168.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/169.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/170.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/171.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/172.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/173.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/174.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/175.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/176.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/177.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/178.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/179.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/180.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/181.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/182.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/183.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/184.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/185.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/186.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/187.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/188.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/189.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/190.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/191.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/192.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/193.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/194.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/195.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/196.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/197.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/198.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/199.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/200.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/201.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/202.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/203.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/204.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/205.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/206.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/207.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/208.jpg', caption: 'Aces Week' },
  { src: '/images/gallery/Aces week/209.jpg', caption: 'Aces Week' },
]

const photos_codefest = [
  { src: '/images/gallery/Codefest/1.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/2.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/3.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/4.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/5.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/6.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/7.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/8.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/9.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/10.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/11.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/12.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/14.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/15.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/16.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/17.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/18.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/19.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/20.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/21.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/22.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/23.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/24.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/25.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/26.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/27.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/28.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/29.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/30.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/31.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/32.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/33.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/34.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/35.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/36.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/37.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/38.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/39.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/40.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/41.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/42.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/43.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/44.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/45.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/46.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/47.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/48.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/49.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/50.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/51.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/52.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/53.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/54.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/55.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/56.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/57.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/58.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/59.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/60.jpg', caption: 'Codefest' },
  { src: '/images/gallery/Codefest/61.jpg', caption: 'Codefest' },
]

const photos_field_trip = [
  { src: '/images/gallery/Field Trip/1.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/2.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/3.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/4.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/5.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/6.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/7.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/8.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/9.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/10.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/11.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/12.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/13.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/14.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/15.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/16.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/17.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/18.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/19.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/20.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/21.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/22.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/23.jpg', caption: 'Field Trip' },
  { src: '/images/gallery/Field Trip/24.jpg', caption: 'Field Trip' },
]

const photos_ladies_general_meeting = [
  { src: '/images/gallery/Ladies general meeting/1.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/2.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/3.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/4.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/5.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/6.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/7.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/8.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/9.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/10.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/11.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/12.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/13.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/14.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/15.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/16.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/17.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/18.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/19.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/20.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/21.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/22.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/23.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/24.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/25.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/26.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/27.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/28.jpg', caption: 'Ladies General Meeting' },
  { src: '/images/gallery/Ladies general meeting/29.jpg', caption: 'Ladies General Meeting' },
]

const photos_medtech_rave = [
  { src: '/images/gallery/MedTech Rave/1.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/2.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/3.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/4.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/5.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/6.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/7.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/8.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/9.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/10.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/11.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/12.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/13.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/14.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/15.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/16.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/17.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/18.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/19.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/20.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/21.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/22.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/23.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/24.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/25.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/26.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/27.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/28.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/29.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/30.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/31.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/32.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/33.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/34.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/35.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/36.jpg', caption: 'MedTech Rave' },
  { src: '/images/gallery/MedTech Rave/37.jpg', caption: 'MedTech Rave' },
]

const photos_orientation = [
  { src: '/images/gallery/orientation/1.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/2.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/3.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/4.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/5.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/6.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/7.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/8.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/9.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/10.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/11.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/12.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/13.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/14.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/15.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/16.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/17.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/18.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/19.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/20.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/21.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/22.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/23.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/24.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/25.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/26.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/27.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/28.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/29.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/30.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/31.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/32.jpg', caption: 'Orientation' },
  { src: '/images/gallery/orientation/33.jpg', caption: 'Orientation' },
]

export const categories: Category[] = [
  {
    slug: 'aces-moments',
    name: 'ACES Moments',
    description: 'Memorable moments from ACES events, trips, and community gatherings.',
    cover: '/images/Acesshirt.jpg',
    count: allPhotos.length,
    photos: allPhotos,
  },
  {
    slug: 'aces-week',
    name: 'Aces Week',
    description: 'Highlights from Aces Week celebrations.',
    cover: '/images/gallery/Aces week/1.jpg',
    count: 208,
    photos: photos_aces_week,
  },
  {
    slug: 'codefest',
    name: 'Codefest',
    description: 'Moments from the annual Codefest competition.',
    cover: '/images/gallery/Codefest/1.jpg',
    count: 60,
    photos: photos_codefest,
  },
  {
    slug: 'field-trip',
    name: 'Field Trip',
    description: 'Photos from ACES educational field trips.',
    cover: '/images/gallery/Field Trip/1.jpg',
    count: 24,
    photos: photos_field_trip,
  },
  {
    slug: 'ladies-general-meeting',
    name: 'Ladies General Meeting',
    description: 'Empowering women in tech — LGM highlights.',
    cover: '/images/gallery/Ladies general meeting/1.jpg',
    count: 29,
    photos: photos_ladies_general_meeting,
  },
  {
    slug: 'medtech-rave',
    name: 'MedTech Rave',
    description: 'Scenes from the MedTech Rave event.',
    cover: '/images/gallery/MedTech Rave/1.jpg',
    count: 37,
    photos: photos_medtech_rave,
  },
  {
    slug: 'orientation',
    name: 'Orientation',
    description: 'Welcoming new members to the ACES family.',
    cover: '/images/gallery/orientation/1.jpg',
    count: 33,
    photos: photos_orientation,
  },
]

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug)
}

